// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fcs.api.Data;

#nullable disable

namespace fcs.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241201195513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("fcs.api.Models.Civilization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Climate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Culture")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Technology")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Civilizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentYear = 0,
                            Name = "Atlantis",
                            Population = 250
                        },
                        new
                        {
                            Id = 2,
                            CurrentYear = 0,
                            Name = "Babylon",
                            Population = 150
                        });
                });

            modelBuilder.Entity("fcs.api.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CivilizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CivilizationId = 1,
                            Description = "Atlantis founded.",
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            CivilizationId = 2,
                            Description = "Babylon rose to power.",
                            Year = 0
                        });
                });

            modelBuilder.Entity("fcs.api.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CivilizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CivilizationId = 1,
                            Name = "Wood",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 2,
                            CivilizationId = 1,
                            Name = "Minerals",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            CivilizationId = 1,
                            Name = "Food",
                            Quantity = 800
                        },
                        new
                        {
                            Id = 4,
                            CivilizationId = 2,
                            Name = "Wood",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            CivilizationId = 2,
                            Name = "Food",
                            Quantity = 500
                        });
                });

            modelBuilder.Entity("fcs.api.Models.Event", b =>
                {
                    b.HasOne("fcs.api.Models.Civilization", "Civilization")
                        .WithMany("Events")
                        .HasForeignKey("CivilizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Civilization");
                });

            modelBuilder.Entity("fcs.api.Models.Resource", b =>
                {
                    b.HasOne("fcs.api.Models.Civilization", "Civilization")
                        .WithMany("Resources")
                        .HasForeignKey("CivilizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Civilization");
                });

            modelBuilder.Entity("fcs.api.Models.Civilization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
